export const CHANGELOG = [
  {
    version: '1.8',
    date: 'Jul 2026',
    entries: [
      'Workout tracking — switch between Skincare and Workouts from the header',
      'Log workouts with exercises: sets, reps, and weight or distance',
      'Training journal grouped by day, with a this-week summary',
      'Workouts get their own calendar, separate from the skincare routine',
      'Track calories per workout — counted into the summaries',
      'Week AND month summary tiles: workouts, minutes, calories, and steps at a glance',
      'Daily step counter — log your steps for today, see them on each day of the journal',
      'Auto-estimate calories from duration, intensity, and your body weight (MET formula)',
      'Change your body weight anytime from Settings → Workout',
      'Workout cards link straight to their spot on the workout calendar',
      'Upcoming workouts are separated from the Past workouts section, with this week\'s highlighted',
      'Upcoming and past workouts are grouped under collapsible month sections',
      'Sort workouts by date, name, duration, calories, or exercise count — ascending or descending',
      'Reset button on sort bars to jump back to the default order',
      'Cards are slightly indented from their section headings for readability',
      'Fixed the Cancel button being too small and its hover highlight not matching its size in the new type, event, and workout forms',
      'Fixed the calendar\'s sort bar shifting position when switching sort options or toggling Reset',
      'Log a location for each workout — e.g. Home, Gym, Park — shown on the card and in the workout calendar',
      'New Trackers section in Settings — turn Skincare and/or Workouts on or off; disabled trackers are hidden from the header entirely',
      'A welcome screen invites you to enable a tracker in Settings if none are turned on',
      'Step logger now targets any past day, not just today — pick the date, then log its count',
      'New Poop tracker (opt-in, off by default) — a simple calendar to log when it happened, enable it from Settings → Trackers',
      'Logging a poop now asks how it felt — shown on the entry afterward',
      'Days with more than one logged poop get a bigger, wobblier marker on the calendar the more there are',
      'Fixed the header\'s tracker switcher overlapping the buttons on the right once a third tracker was enabled — the header now wraps onto its own line instead, and trackers never shrink or lose their labels',
      'Redesigned the header\'s right side — changelog, calendar, and settings now sit in one grouped pill (matching the tracker switch) that stays in the same order and position across every tracker',
      'Calendar button no longer shows for Poop (it has no separate calendar screen to open) — no leftover empty gap in the header',
      'Moved the item count ("X products"/"X workouts"/"X logged") to its own line below the tracker switch, so it no longer competes for space and pushes the header buttons onto a second row',
      'Removed the standalone "New category" and "Add type" buttons — the + button now opens a small animated menu to add a Category, Type, or Product',
      'Select mode on every tracker — tap Select, pick items, then Delete N to bulk-remove them, with a summary popup that needs two taps to confirm',
      'Sort a day\'s poop entries by Time or Feeling, ascending or descending',
      'More stages to the calendar\'s poop marker — up to 7, escalating in size, wobble speed, and eventually a glow the busier the day gets',
      'Each day on the poop calendar now shows its exact count as a small badge, alongside the marker',
      'Daily average summary above the poop calendar, scoped to whichever month you\'re viewing — flip months to see that month\'s average',
      'New "Custom" sort for poop entries — drag to reorder a day\'s list by hand; switching to Time/Feeling and back always restores your custom order exactly as you left it',
      'New Friends menu (Google-linked accounts only) — everyone gets a short friend code; send a request with someone else\'s code, and once they accept you can view each other\'s Skincare, Workouts, and Poop trackers read-only. Both calendars stay private no matter what',
      'Go Private in the Friends menu to block incoming friend requests — friends you already have aren\'t affected',
      'Give each friend a nickname so they show up as "Bob" instead of their code',
      'Tap View next to a friend to open their shared profile — it stays open until you tap Exit, even if you switch your own tracker in the background',
      'Unfriending someone removes them from both friend lists instantly, no confirmation needed from the other side',
      'Moved the skincare "+" button from a floating circle at the bottom to a large button at the top of the list — the Category/Type/Product menu now drops down below it instead of growing upward',
    ],
  },
  {
    version: '1.7',
    date: 'Jul 2026',
    entries: [
      'Routine calendar — schedule skincare events on specific dates',
      'Events get a name, emoji, duration, time of day, and a precise time',
      'Link a calendar event to an existing product',
      'Product cards show their linked dates — tap one to jump straight to that event',
      'Expired products automatically surface in their own Expired section',
      'Small calendar icon on a card shows it has a linked event',
      '"Add type" is now one control that lets you pick the category, instead of repeating in every category',
      'Drag to reorder types within their category',
      'Toast confirmation when adding a new product',
      'Add types within a category — sub-categories to organize products further',
      'Drag products into a type, or assign one from the product card',
      'Type picker on the product card lets you select an existing type or create a new one on the fly, with its own emoji',
      'Cards no longer collapse when their category or type changes',
      'Filter the product list by category and type when linking a calendar event',
      'Hide expired products from that list with one checkbox',
      'Removed the category suggestions section',
      'Added 1 month and 2 month options to "Use within"',
      'Emoji picker expanded to 126 options — hair, spa, sun protection, packaging, mindfulness, and more',
      'Emoji picker now has a "+" option to type or paste any emoji from your own keyboard',
      'Sort a day\'s calendar events by Time, Name, or Duration',
      'Tap the active sort again to flip between ascending/descending — an arrow shows the current direction',
      'Precise time picker replaced with hour/minute dropdowns — guarantees 24h format on every device',
      'Opening/expiration date fields now open the calendar from a tap anywhere in the box, not just a tiny corner',
    ],
  },
  {
    version: '1.6',
    date: 'May 2026',
    entries: [
      'New settings panel to customize app appearance',
    ],
  },
  {
    version: '1.5',
    date: 'May 2026',
    entries: [
      'Drag products across categories to reassign them instantly',
      'Live drag preview — dragged item follows your cursor or finger across the whole screen',
      'Items in the list shuffle in real time to show where the product will land',
      'What\'s new button in the header with an unread indicator',
    ],
  },
  {
    version: '1.4',
    date: 'May 2026',
    entries: [
      'Categories with drag-and-drop reordering',
      'Preset category suggestions (Cleansers, Serums, Sunscreen…)',
      'Assign products to categories from the product card',
    ],
  },
  {
    version: '1.3',
    date: 'May 2026',
    entries: [
      'Cloud sync — products saved across all your devices',
      'Automatic anonymous sign-in on first visit',
      'Optional Google account linking to keep data permanently',
    ],
  },
  {
    version: '1.2',
    date: 'May 2026',
    entries: [
      'Light and dark mode',
      'Follows your system preference with no flash on load',
    ],
  },
  {
    version: '1.1',
    date: 'May 2026',
    entries: [
      'Photo upload for products',
      'Dedicated camera FAB button to add a product with a photo instantly',
    ],
  },
  {
    version: '1.0',
    date: 'May 2026',
    entries: [
      'Track skincare products with name, opening date and expiration date',
      'Status indicators: Sealed, Open, Expiring Soon, Expired',
      'Auto-suggest expiration date from opening date + usage months',
      'DD/MM/YYYY date format throughout',
    ],
  },
]

export const LATEST_VERSION = CHANGELOG[0].version

