// Newest release first — CHANGELOG[0] is what LATEST_VERSION reports and
// what the modal badges as "New". Each release gets a short `title` so the
// list stays readable when several shipped in the same month.
export const CHANGELOG = [
  {
    version: '2.6',
    title: 'Notes tracker',
    date: 'Sep 2026',
    entries: [
      'New Notes tracker — plain typed notes, enable it from Settings → Trackers',
      'Organise notes three levels deep: a project holds categories, a category holds notes, and a note can sit directly in a project or in nothing at all',
      'Projects, categories and the Unfiled section are all allowed to be empty — nothing has to be filed anywhere',
      'Every note has an In field: open a note, tap Edit, and pick the project, category or Unfiled it should live in — no dragging needed. The same field is on the add form, so a new note can be filed somewhere other than the section you started from',
      'Editing a category lets you pick which project it belongs to, or take it out of one entirely — every note inside comes along',
      'Drag any note into any project, any category, or straight out to Unfiled, and reorder it wherever it lands',
      'Drag a whole category into a project or back out to the top level — every note inside it comes along',
      'Drag projects to reorder the sections themselves',
      'Deleting a project or a category never deletes what is inside it: the notes move up one level instead, so nothing is lost by tidying up',
      'Add a note, a category or a project from wherever you already are — every section header has its own labelled buttons',
      'Rename or re-emoji any project or category from its ··· menu, same as skincare categories',
      'Tap a note to read it in full, with Edit and Delete underneath; collapsed it shows one line of the body',
      'A view picker at the top of the tracker narrows it to one project (its categories and notes), one category (just its notes), or the Unfiled notes on their own — with a count next to every option and a Show all button to come back',
      'The picker is a proper menu rather than a plain dropdown: every option carries its own emoji, its note count, and the project it sits in, grouped under Projects and Categories headings, and it works from the keyboard with the arrow keys',
      'While a project or category is showing on its own, Add note puts the note straight into it rather than into Unfiled, and says so on the button',
      'The chosen view is remembered between visits, and falls back to showing everything if what it pointed at is deleted',
      'Select mode on the Notes tracker — pick notes across every project and bulk-delete them, with each one showing where it lives before you confirm',
      'Notes joins the friend-sharing system with its own visibility toggle in Settings → Privacy',
    ],
  },
  {
    version: '2.5',
    title: 'Expiry warnings & duplicates',
    date: 'Sep 2026',
    entries: [
      'New Expiring button at the top of the skincare tracker — every open or sealed product with less than 12 months left on its date, plus sealed products already past theirs, soonest first and cutting across all your categories. Tap one to jump straight to its card',
      'Set a "Send warning" date on any product: from that day the card counts down the days left, sealed or open. The reminder notification itself lands in a later update',
      'Sealed products now show how much of their printed date is left, in a second chip beside the Sealed badge — no more guessing which sealed jar to open first',
      'Long horizons read as months or years instead of a four-digit day count: "3yrs left" rather than "1094d left". The last month still counts in days, then it is months up to a year and years beyond that',
      'Dates can now be typed straight in as DD/MM/YYYY, on top of the presets and the calendar picker — the slashes fill themselves in as you type',
      'Say how many of a product you have: a quantity with − and + buttons on the card, or type the number straight in. Anything above one shows at the end of the name, so six sunscreens read as one card rather than six',
      'The "Use within" period now takes any number of months from 1 to 24, on a slider under the dropdown. The common periods are still one tap away in the dropdown itself',
      'Added a 9 month option to "Use within" on products',
      'Ticked-off tasks now collect in their own Completed section at the bottom of the tasks tracker, newest first — they leave Today, This week, Expired, Future and Undated the moment you check them, so an old task can no longer sit in Expired nagging you after it is done',
    ],
  },
  {
    version: '2.4',
    title: 'Task dates & Expired',
    date: 'Sep 2026',
    entries: [
      'Overdue tasks moved out of Today into their own Expired list, sitting beside Future with the same drag-to-resize divider and collapse-to-rail as Today and This week',
      'Every task now shows its own date on the card: the normal text colour for today, blue for anything still coming up, red once it is overdue — with how late it already is alongside it',
      'Day headings are gone from the task lists — now that each task carries its date, the tasks in a list run as one continuous column',
      'Adding a task from the Expired list dates it yesterday, so it stays in the list you added it from',
    ],
  },
  {
    version: '2.3',
    title: 'Tasks tracker',
    date: 'Aug 2026',
    entries: [
      'New Tasks tracker — a to-do list split into Today, This week, Future and Undated, enable it from Settings → Trackers',
      'Drag the divider between Today and This week to give either side more room, or collapse one entirely into a side rail — your layout is remembered',
      'Tasks are always ordered by date first: each section groups into days, and a task\'s category never pulls it out of its day',
      'Overdue tasks roll into Today under their own dated heading, flagged with how late they are',
      'Future tasks are grouped into collapsible months, soonest first',
      'Give a task a category (one) and any number of labels — both with their own emoji',
      'Colour your labels — 8 colours, picked from a swatch row with a live preview of the finished chip',
      'Create a category or label inline while writing a task, and tap Edit next to Labels to rename, recolour or delete one later',
      'Check a task off and it stays exactly where it is, dimmed and struck through',
      'Drag to reorder tasks within a single day, and tap any task for its notes, Edit and Delete',
      'The add/edit form opens full width under the add bar, scrolls itself into view, and outlines the task it belongs to',
      'Select mode on the Tasks tracker — pick tasks across every section and bulk-delete them, same two-tap confirm as everywhere else',
      'Tasks joins the friend-sharing system with its own visibility toggle in Settings → Privacy',
      'Widened the whole app from 544px to 704px of content — every tracker gets more room to breathe',
      'Emoji picker now fits 8 per row instead of 6, in a taller panel',
    ],
  },
  {
    version: '2.2',
    title: 'Steps insights',
    date: 'Jul 2026',
    entries: [
      'Workout summary split into its own Workouts and Steps tiles, with a Week/Month switch above them',
      'Month view on the summary tiles — workouts, minutes, calories and steps for a whole month, not just this week',
      'Tap the Steps tile to open a bar graph of steps for each day of the week or month',
      'Hover or tap any bar on the steps graph to see that exact day\'s count and date',
      'Fixed the steps tile showing empty when viewing a friend\'s shared profile',
    ],
  },
  {
    version: '2.1',
    title: 'Positions tracker',
    date: 'Jul 2026',
    entries: [
      'New Positions tracker (🔞 18+, off by default) — a scratch-off grid of sex positions, enable it from Settings behind a clear explicit-content warning',
      'Scratch any card to reveal it, or tap "Reveal random position" to have one stand out from the grid for you to scratch',
      'Check a revealed position as experienced whenever you feel like it — the date shows right on the card',
      'Positions grid grown from 26 to 106 cards to scratch through',
      'Select mode on the Positions tracker — pick any revealed cards and hide them back under their cover, same Select/confirm pattern as every other tracker',
      'The Positions tracker is never shared with friends, no matter your tracker visibility settings — it has no shared/read-only view at all',
      'Fixed scratching a Positions card trapping the whole touch gesture on mobile, blocking you from scrolling past the grid',
      'Fixed Positions cards scratching while scrolling on mobile — a swipe now commits to either scrolling or scratching, never both, and scratching itself reveals faster',
      'Fixed holding down on a Positions card triggering the phone\'s native text-selection/callout menu',
    ],
  },
  {
    version: '2.0',
    title: 'Friends & sharing',
    date: 'Jul 2026',
    entries: [
      'New Friends menu (Google-linked accounts only) — everyone gets a short friend code; send a request with someone else\'s code, and once they accept you can view each other\'s Skincare, Workouts, and Poop trackers read-only. Both calendars stay private no matter what',
      'Tap View next to a friend to open their shared profile — it stays open until you tap Exit, even if you switch your own tracker in the background',
      'Give each friend a nickname so they show up as "Bob" instead of their code',
      'Unfriending someone removes them from both friend lists instantly, no confirmation needed from the other side',
      'Go Private to block incoming friend requests — friends you already have aren\'t affected',
      'Tracker visibility setting — choose one visibility for all trackers, or set Skincare/Workouts/Poop separately, controlling what friends can see once they\'re added',
      'Explained what Visible/Hidden actually do in the Tracker visibility setting',
      'Moved "Who can add you" and "Tracker visibility" out of the Friends menu into a new Privacy section in Settings',
      'The Friends menu slides in over the tracker instead of opening as a popup',
      'Your tracker switch stays visible and tappable while the Friends menu is open, so you can jump straight to a tracker without closing it first',
      'Redesigned the friends list — each friend now gets a card with an avatar initial, replacing the plain list row',
      '"Add a friend" is now a button that opens a popup for the code, instead of an always-visible input field',
      'Mark a product as empty from its card — it moves into its own Empty section (like Expired), showing the date you emptied it',
    ],
  },
  {
    version: '1.9',
    title: 'Poop tracker',
    date: 'Jul 2026',
    entries: [
      'New Poop tracker (opt-in, off by default) — a simple calendar to log when it happened, enable it from Settings → Trackers',
      'Logging a poop now asks how it felt — shown on the entry afterward',
      'Days with more than one logged poop get a bigger, wobblier marker on the calendar the more there are — up to 7 stages, escalating in size, wobble speed, and eventually a glow',
      'Each day on the poop calendar shows its exact count as a small badge, alongside the marker',
      'Daily average summary above the poop calendar, scoped to whichever month you\'re viewing — flip months to see that month\'s average',
      'Sort a day\'s poop entries by Time or Feeling, ascending or descending',
      'New "Custom" sort for poop entries — drag to reorder a day\'s list by hand; switching to Time/Feeling and back always restores your custom order exactly as you left it',
      'Select mode on every tracker — tap Select, pick items, then Delete N to bulk-remove them, with a summary popup that needs two taps to confirm',
      'Moved the Poop tracker\'s Select button off its own row, next to the day\'s sort options — same treatment as the Workout journal',
      'Removed the standalone "New category" and "Add type" buttons — the + button now opens a small animated menu to add a Category, Type, or Product',
      'Moved the skincare "+" button from a floating circle at the bottom to a large button at the top of the list — the Category/Type/Product menu now drops down below it instead of growing upward',
      'Redesigned the header\'s right side — changelog, calendar, and settings now sit in one grouped pill (matching the tracker switch) that stays in the same order and position across every tracker',
      'Moved the item count ("X products"/"X workouts"/"X logged") to its own line below the tracker switch, so it no longer competes for space and pushes the header buttons onto a second row',
      'Calendar button no longer shows for Poop (it has no separate calendar screen to open) — no leftover empty gap in the header',
      'Fixed the header\'s tracker switcher overlapping the buttons on the right once a third tracker was enabled — the header now wraps onto its own line instead, and trackers never shrink or lose their labels',
    ],
  },
  {
    version: '1.8',
    title: 'Workout tracking',
    date: 'Jul 2026',
    entries: [
      'Workout tracking — switch between Skincare and Workouts from the header',
      'Log workouts with exercises: sets, reps, and weight or distance',
      'Training journal grouped by day, with a this-week summary',
      'Workouts get their own calendar, separate from the skincare routine',
      'Workout cards link straight to their spot on the workout calendar',
      'Track calories per workout — counted into the summaries',
      'Auto-estimate calories from duration, intensity, and your body weight (MET formula)',
      'Change your body weight anytime from Settings → Workout',
      'Log a location for each workout — e.g. Home, Gym, Park — shown on the card and in the workout calendar',
      'Daily step counter — log your steps for any day, not just today, and see them on each day of the journal',
      'Upcoming workouts are separated from the Past workouts section, with this week\'s highlighted',
      'Upcoming and past workouts are grouped under collapsible month sections',
      'Sort workouts by date, name, duration, calories, or exercise count — ascending or descending',
      'Reset button on sort bars to jump back to the default order',
      'New Trackers section in Settings — turn Skincare and/or Workouts on or off; disabled trackers are hidden from the header entirely',
      'A welcome screen invites you to enable a tracker in Settings if none are turned on',
      'Cards are slightly indented from their section headings for readability',
      'Fixed the Cancel button being too small and its hover highlight not matching its size in the new type, event, and workout forms',
      'Fixed the calendar\'s sort bar shifting position when switching sort options or toggling Reset',
    ],
  },
  {
    version: '1.7',
    title: 'Types & routine calendar',
    date: 'Jul 2026',
    entries: [
      'Routine calendar — schedule skincare events on specific dates',
      'Events get a name, emoji, duration, time of day, and a precise time',
      'Link a calendar event to an existing product',
      'Product cards show their linked dates — tap one to jump straight to that event',
      'Small calendar icon on a card shows it has a linked event',
      'Filter the product list by category and type when linking a calendar event',
      'Hide expired products from that list with one checkbox',
      'Sort a day\'s calendar events by Time, Name, or Duration',
      'Tap the active sort again to flip between ascending/descending — an arrow shows the current direction',
      'Add types within a category — sub-categories to organize products further',
      'Drag products into a type, or assign one from the product card',
      'Type picker on the product card lets you select an existing type or create a new one on the fly, with its own emoji',
      'Drag to reorder types within their category',
      '"Add type" is now one control that lets you pick the category, instead of repeating in every category',
      'Cards no longer collapse when their category or type changes',
      'Expired products automatically surface in their own Expired section',
      'Toast confirmation when adding a new product',
      'Emoji picker expanded to 126 options — hair, spa, sun protection, packaging, mindfulness, and more',
      'Emoji picker now has a "+" option to type or paste any emoji from your own keyboard',
      'Precise time picker replaced with hour/minute dropdowns — guarantees 24h format on every device',
      'Opening/expiration date fields now open the calendar from a tap anywhere in the box, not just a tiny corner',
      'Added 1 month and 2 month options to "Use within"',
      'Removed the category suggestions section',
    ],
  },
  {
    version: '1.6',
    title: 'Appearance settings',
    date: 'May 2026',
    entries: [
      'New settings panel to customize app appearance',
    ],
  },
  {
    version: '1.5',
    title: 'Drag across categories',
    date: 'May 2026',
    entries: [
      'Drag products across categories to reassign them instantly',
      'Live drag preview — dragged item follows your cursor or finger across the whole screen',
      'Items in the list shuffle in real time to show where the product will land',
      'What\'s new button in the header with an unread indicator',
    ],
  },
  {
    version: '1.4',
    title: 'Categories',
    date: 'May 2026',
    entries: [
      'Categories with drag-and-drop reordering',
      'Preset category suggestions (Cleansers, Serums, Sunscreen…)',
      'Assign products to categories from the product card',
    ],
  },
  {
    version: '1.3',
    title: 'Cloud sync',
    date: 'May 2026',
    entries: [
      'Cloud sync — products saved across all your devices',
      'Automatic anonymous sign-in on first visit',
      'Optional Google account linking to keep data permanently',
    ],
  },
  {
    version: '1.2',
    title: 'Light & dark mode',
    date: 'May 2026',
    entries: [
      'Light and dark mode',
      'Follows your system preference with no flash on load',
    ],
  },
  {
    version: '1.1',
    title: 'Photos',
    date: 'May 2026',
    entries: [
      'Photo upload for products',
      'Dedicated camera FAB button to add a product with a photo instantly',
    ],
  },
  {
    version: '1.0',
    title: 'First release',
    date: 'May 2026',
    entries: [
      'Track skincare products with name, opening date and expiration date',
      'Status indicators: Sealed, Open, Expiring Soon, Expired',
      'Auto-suggest expiration date from opening date + usage months',
      'DD/MM/YYYY date format throughout',
    ],
  },
]

export const LATEST_VERSION = CHANGELOG[0].version
